/*
 * Copyright © 2020 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.sudoplatform.sudovirtualcards.types.inputs

import com.sudoplatform.sudovirtualcards.types.BillingAddress
import java.util.UUID

/**
 * A request to provision a virtual payment card.
 *
 * @property clientRefId A reference identifier generated by the caller.
 * @property sudoId Identifier of the [com.sudoplatform.sudoprofiles.Sudo] to provision a card for.
 * @property fundingSourceId Identifier of the associated funding source used to fund the provisioned card.
 * @property cardHolder The name on the front of the card.
 * @property alias User defined name associated with the card.
 * @property billingAddress [BillingAddress] associated with the card. If not supplied, the default billing address will be used.
 * @property currency The ISO 4217 currency code.
 */
data class ProvisionCardInput(
    val clientRefId: String = UUID.randomUUID().toString(),
    val sudoId: String,
    val fundingSourceId: String,
    val cardHolder: String,
    val alias: String,
    val billingAddress: BillingAddress? = null,
    val currency: String
) {
    constructor(
        clientRefId: String = UUID.randomUUID().toString(),
        sudoId: String,
        fundingSourceId: String,
        cardHolder: String,
        alias: String,
        addressLine1: String,
        addressLine2: String? = null,
        city: String,
        state: String,
        postalCode: String,
        country: String,
        currency: String
    ) : this(
        clientRefId = clientRefId,
        sudoId = sudoId,
        fundingSourceId = fundingSourceId,
        cardHolder = cardHolder,
        alias = alias,
        billingAddress = BillingAddress(addressLine1, addressLine2, city, state, postalCode, country),
        currency = currency
    )
}
