/*
 * Copyright © 2020 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.sudoplatform.sudovirtualcards.types

import java.util.Date

/**
 * A card that is in the process of being provisioned.
 *
 * @property id Identifier generated by the Virtual Cards Service.
 * @property clientRefId A reference identifier generated by the caller
 * @property owner Identifier of the user that owns the card.
 * @property version Card version supplied by the Virtual cards service.
 * @property state Current state of the provisional card.
 * @property card Fully provisioned card, will be null until provisioning completes.
 * @property createdAt [Date] when the provisional card was created
 * @property updatedAt [Date] when the provisional card was last updated
 *
 * @since 2020-06-11
 */
data class ProvisionalCard(
    val id: String,
    val clientRefId: String,
    val owner: String,
    val version: Int,
    val state: State,
    val card: Card?,
    val createdAt: Date,
    val updatedAt: Date
) {
    /** State of the provisional card. */
    enum class State {
        /** Card is in a provisioning state currently. */
        PROVISIONING,
        /**
         * Card has been provisioned which means the card should be accessible by either a getCard API
         * or via [card] property.
         */
        COMPLETED,
        /** Card is in a failed state and needs to be rectified. */
        FAILED,
        /** API Evolution - if this occurs, it may mean you need to update the library. */
        UNKNOWN
    }
}
