/*
 * Copyright © 2020 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.sudoplatform.sudovirtualcards.types

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
import java.util.Date

/**
 * Representation of a Virtual Card Transaction used in the Sudo Platform SDK.
 *
 * @property id Identifier generated by the Virtual Cards Service for this transaction.
 * @property owner Identifier of the user that owns the card.
 * @property version Card version supplied by the Virtual cards service.
 * @property cardId Unique identifier of the [Card]
 * @property sequenceId The sequence identifier of the transaction
 * @property type The type of the transaction
 * @property billedAmount The amount billed for the transaction
 * @property transactedAmount The amount of the transaction
 * @property description The description of the transaction
 * @property declineReason If the transaction was declined the reason why, null if the transaction was not declined.
 * @property details The details of how the transaction was charged
 * @property transactedAt [Date] when the transaction was performed
 * @property createdAt [Date] when the transaction was created
 * @property updatedAt [Date] when the transaction was last updated
 *
 * @since 2020-07-16
 */
@Parcelize
data class Transaction(
    val id: String,
    val owner: String,
    val version: Int,
    val cardId: String,
    val sequenceId: String,
    val type: Type,
    val billedAmount: CurrencyAmount,
    val transactedAmount: CurrencyAmount,
    val description: String,
    val declineReason: DeclineReason? = null,
    val details: List<TransactionChargeDetail> = emptyList(),
    val transactedAt: Date,
    val createdAt: Date,
    val updatedAt: Date
) : Parcelable {
    /** Transaction type */
    enum class Type {
        /** Transaction is still being processed */
        PENDING,
        /** Transaction has been completely processed */
        COMPLETE,
        /** The transaction is a refund */
        REFUND,
        /** The transaction is the decline of a charge */
        DECLINE,
        /** API Evolution - if this occurs, it may mean you need to update the library. */
        UNKNOWN
    }
}
